#ifndef BROKER_GLOBAL_H
#define BROKER_GLOBAL_H

#ifndef BROKER_SERVER_BUILD
#define BROKER_SERVER_BUILD IOT_DSA_C_SDK_GIT_COMMIT_HASH
#endif

#ifndef BROKER_DSA_VERSION
#define BROKER_DSA_VERSION "1.1.2"
#endif

#endif //BROKER_GLOBAL_H
